apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: rta
      defaultBucket: fraud_alerts
      tlsSkipVerify: true
    secureJsonData:
      token: rta-super-secret-token
    isDefault: true
    editable: false
